//
// Created by maiikeru on 5/10/15.
//

#ifndef RESULT_LUTTABLE_H
#define RESULT_LUTTABLE_H

#include <iostream>




const std::string LUT_image_filename[] = {
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/0.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/1.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/2.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/3.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/4.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/5.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/6.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/7.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/8.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/9.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/10.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/11.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/12.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/13.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/14.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/15.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/16.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/17.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/18.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/19.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/20.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/21.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/22.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/23.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/24.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/25.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/26.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/27.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/28.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/29.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/30.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/31.png",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/32.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/33.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/34.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/35.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/36.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/37.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/38.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/39.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/40.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/41.jpg",
        "/home/maiikeru/bitbucket/BP-road-sign-detection/data_sets/icons/42.jpg",

};



const static std::string LUT_table_name[] = {
        "Nejvyšší povolená rychlost 20 ",
        "Nejvyšší povolená rychlost 30",
        "Nejvyšší povolená rychlost 50",
        "Nejvyšší povolená rychlost 60",
        "Nejvyšší povolená rychlost 70",
        "Nejvyšší povolená rychlost 80",
        "Konec nejvyšší povolené rychlosti 80",
        "Nejvyšší povolená rychlost 100",
        "Nejvyšší povolená rychlost 120",
        "Zákaz předjíždění",
        "Zákaz předjíždění pro nákladní automobily",
        "Křižovatka s vedlejší pozemní komunikací",
        "Hlavní pozemní komunikace",
        "Dej přednost v jízdě",
        "Stůj, dej přednost v jízdě",
        "Zákaz vjezdu všech vozidel(v obou směrech)",
        "Zákaz vjezdu nákladních automobilů",
        "Zákaz vjezdu všech vozidel",
        "Jiné nebezpečí",
        "Zatáčka vlevo",
        "Zatáčka vpravo",
        "Dvojitá zatáčka,první vlevo",
        "Nerovnost vozovky",
        "Nebezpečí smyku",
        "Zúžená vozovka (zjedné strany)",
        "Práce",
        "Světelné signály",
        "Zákaz vstupu chodcu",
        "Děti",
        "Cyklisté",
        "Náledí",
        "Zvěř",
        "Konec všech zákazů",
        "Přikázaný směr jízdy vpravo",
        "Přikázaný směr jízdy vlevo",
        "Přikázaný směr jízdy přímo",
        "Přikázaný směr jízdy přímo a vpravo",
        "Přikázaný směr jízdy přímo a vlevo",
        "Přikázaný směr objíždění vpravo",
        "Přikázaný směr objíždění vlevo",
        "Kruhový objezd",
        "Konec zákazu předjíždění",
        "Konec zák. před. pro nákladní automobily",
        "Okoli",
};

const static std::string LUT_table_class[] = {
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Dopravní značka upravující přednost",
        "Dopravní značka upravující přednost",
        "Dopravní značka upravující přednost",
        "Dopravní značka upravující přednost",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Zákazová dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Výstražná dopravní značka",
        "Zákazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Příkazová dopravní značka",
        "Zákazová dopravní značka",
        "Zákazová dopravní značka",
        "Okoli",
};

#endif //RESULT_LUTTABLE_H
